# general settings
name: TVQRAP_stage1
model_type: TVQRAP_stage1_Model
num_gpu: 4
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: Imagnet
    type: Imagenet_stage1_Dataset
    dataroot_gt: .../.../.../imagenet_train_dir
    filename_tmpl: '{}'
    io_backend:
      type: disk

    in_size: 512
    gt_size: 512
    mean: [0.5, 0.5, 0.5]
    std: [0.5, 0.5, 0.5]
    use_hflip: true

    # data loader
    num_worker_per_gpu: 2
    batch_size_per_gpu: 2
    dataset_enlarge_ratio: 1

    prefetch_mode: cpu
    num_prefetch_queue: 8

  val:
    name: Imagnet
    type: Imagenet_stage1_Dataset
    dataroot_gt: .../.../.../imagenet256-test/gt_dir
    filename_tmpl: '{}'
    io_backend:
      type: disk

    in_size: 256
    gt_size: 256
    mean: [0.5, 0.5, 0.5]
    std: [0.5, 0.5, 0.5]
    use_hflip: False
    is_val: true


    
# network structures
network_g:
  type: VQAutoEncoder
  ch_mult: [1, 2, 2, 4, 2 , 1]
  res_blocks: 2
  codebook_size: 1024


network_d:
  type: VQGANDiscriminator
  input_nc: 3
  n_layers: 2
  ndf: 64
   

# path
path:
  pretrain_network_g: ~
  param_key_g: params_ema
  strict_load_g: true
  pretrain_network_d: ~
  strict_load_d: true
  resume_state: ~

train:
  optim_g:
    type: Adam
    lr: 4.0e-5
    weight_decay: 0
    betas: [0.5, 0.9]
  optim_d:
    type: Adam
    lr: 4.0e-5
    weight_decay: 0
    betas: [0.5, 0.9]


  scheduler:
    type: MultiStepLR
    milestones: [600000000]
    gamma: 1

  total_iter: 450000

  warmup_iter: -1  # no warm up
  ema_decay: 0.995 # GFPGAN: 0.5**(32 / (10 * 1000) == 0.998; Unleashing: 0.995

  pixel_opt:
    type: MSELoss
    loss_weight: 1.0
    reduction: mean

  perceptual_opt:
    type: LPIPSLoss
    loss_weight: 1.0
    use_input_norm: true
    range_norm: true

  gan_opt:
    type: GANLoss
    gan_type: hinge
    loss_weight: !!float 1.0  # adaptive_weighting

  net_g_start_iter: 0
  net_d_iters: 1
  net_d_start_iter: 0
  manual_seed: 0
  disc_weight: 0.75

# validation settings
val:
  val_freq: 50000 # no validation
  save_img: true

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: 50000
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29405

find_unused_parameters: true
